-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Yhtye CASCADE;
DROP TABLE IF EXISTS Esiintymispaikka CASCADE;
DROP TABLE IF EXISTS Keikka CASCADE;
